#!/usr/local/bin/bash
wlan=iwn0
conffile=/etc/wlans
logfile=/var/log/wlanstart
pidfile=/var/run/wlanstart

OIFS=$IFS

redirect_fds() {
  [[ -t 0 ]] && exec</dev/null
  [[ -t 1 ]] && exec >"$logfile"
  [[ -t 2 ]] && exec >"$logfile"
  eval exec {3..255}\>\&-
}

daemonize() {
  redirect_fds()
  cd /
  umask 0
  trap '' 1 2
  echo $$ > $pidfile
}

daemonize()

while true;
  do
    status=$(ifconfig $wlan | grep -E "^[[:blank:]]+status:" | awk {'print $2'})
    echo "status: $status"
    case $status in
    *active*)
      #do nothing
      ;;
    *)
      #find networks
      ifconfig $wlan down
      nets="$(ifconfig $wlan scan | sed -n -E 's/^[[:space:]]+nwid ([[:graph:]]+).*/\1/p')" 
      ournets="$(cat "$conffile")"
      echo "$ournets"
      IFS='
'
      for curnet in $ournets;
        do
          IFS="$OIFS"
          echo "curnet: $curnet"
          nwid=$(echo "$curnet" | awk '{print $1;}')
          if echo "$nets" | grep "^$nwid$" >/dev/null; then
            #set up this network
            echo "ifconfig $wlan up nwid $curnet"
            ifconfig $wlan up nwid $curnet
            dhclient $wlan
            break
          fi
      done ;;
    esac
    sleep 5
done &


